version: '2'
services:
  nginx:
    image: nginx
    container_name: sample-project-nginx
    ports:
     - "80:80"
    links:
     - php
    volumes:
     - ../app:/usr/share/nginx/app
     - ./nginx/logs:/var/log/nginx
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx/sample-project.conf:/etc/nginx/conf.d/sample-project.conf:ro
  php:
    build: php/
    image: sample-project-php-7-dev
    container_name: sample-project-php
    volumes:
     - ../app:/usr/share/nginx/app
     - ./php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini:ro
    environment:
      - ENV_NAME=local
